document.write("<div id=\"content_footer\"></div>");
document.write("<div id=\"footer\">");
document.write("<div id=\"Copyright\" style=\"height:24px;line-height:24px;\">");
document.write("Copyright &copy; Dexiang Zong  | All Rights Reserved");
document.write("</div>");
cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cspan id='cnzz_stat_icon_1253214442'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s5.cnzz.com/z_stat.php%3Fid%3D1253214442%26online%3D1%26show%3Dline' type='text/javascript'%3E%3C/script%3E"));
document.write("</div>");
document.write("</div>");
;