document.write("<div id=\"logo\">");
document.write("<div id=\"logo_text\">");
document.write("<!-- class=\"logo_colour\", allows you to change the colour of the text -->");
document.write("<h1><a href=\"index.html\">梦想可以改变世界<span class=\"logo_colour\"></span></a></h1>");
document.write("<h2>梦想改变世界。</h2>");
document.write("</div>");
document.write("<div id=\"logo_badgeHIT\" class=\"logo_badge\">");
document.write("<a href=\"http://www.hit.edu.cn\" target=\"_blank\"><img src=\"Images/HIT.png\" title=\"哈尔滨工业大学\" height=\"120\"></a>");
//document.write("</div>");
//document.write("<div id=\"logo_badgeHITROBOT\" class=\"logo_badge\">");
//document.write("<a href=\"http://sme.hit.edu.cn\" target=\"_blank\"><img src=\"Images/HITROBOT.png\" title=\"宇航空间机构及控制实验室\" height=\"120\"></a>");
//document.write("</div>");
//document.write("<div id=\"logo_badgeBaosteel\" class=\"logo_badge\">");
//document.write("<a href=\"http://rnd.baosteel.com\" target=\"_blank\"><img src=\"Images/Baosteel.png\" title=\"宝山钢铁股份有限公司研究院\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeXJTU\" class=\"logo_badge\">");
document.write("<a href=\"http://www.xjtu.edu.cn\" target=\"_blank\"><img src=\"Images/xjtu.png\" title=\"西安交通大学\" height=\"120\"></a>");
//document.write("</div>");
//document.write("<div id=\"logo_badgeXJTUAIAR\" class=\"logo_badge\">");
//document.write("<a href=\"http://www.aiar.xjtu.edu.cn\" target=\"_blank\"><img src=\"Images/XJTUAIAR.png\" title=\"西安交大人工智能与机器人研究所\" height=\"120\"></a>");
document.write("</div>");
document.write("</div>");