document.write("<div id=\"menubar\">");
document.write("<ul id=\"menu\">");
document.write("<li><a href=\"../index.html\">Home</a></li>");
//document.write("<li><a href=\"../Teaching.html\">Teaching</a></li>");
document.write("<li><a href=\"../Publication.html\">Publication</a></li>");
//document.write("<li><a href=\"../Project.html\">Project</a></li>");
//document.write("<li><a href=\"../Award.html\">Award</a></li>");
//document.write("<li class=\"selected\"><a href=\"../Blog.html\">Blog</a></li>");
document.write("<li><a href=\"../Link.html\">Link</a></li>");
document.write("<li><a href=\"../AboutMe.html\">AboutMe</a></li>");
document.write("</ul>");
document.write("</div>");